### ISSUE TITLE
x64 FMA ASM excluded from building by default

### ISSUE THREAD

**Issue by Kogarou-san** [jpsdr/NNEDI3#13]
In the latest commit https://github.com/jpsdr/NNEDI3/commit/ec3d992227cea6fe885c34137385c6a99c9f5c3b, nnedi3_asm_FMA_x64.asm is excluded from building from all x64 configurations, leading to linking failures by default.
![image](https://github.com/jpsdr/NNEDI3/assets/7327868/9191d714-4d25-42a5-9c10-10d8bc65ba08)
Please include the file in the build, in the next git commit. Thank you.

**Comment by jpsdr** [comment]
I keep on Github the project on VS2010, wich is unable to compile FMA, this is why they are excluded.
You have to enable them on your project, if you're using a more recent VS version.
This will not change.
