### ISSUE TITLE
System Exception - Illegal Instruction

### ISSUE THREAD

**Issue by kaefert** [jpsdr/NNEDI3#3]
I'm trying to use nnedi3 in avisynth+ 64bit.
I've downloaded the package
https://github.com/jpsdr/NNEDI3/releases/download/v0.9.4.7/NNEDI3_v0_9_4_7.7z

and used this file in my script (on my windows server 2008 with xenon cpu):
NNEDI3_v0_9_4_7/x64/Release_Intel_W7_Xeon_AVX512/nnedi3.dll

the first call to `nnedi3_rpow2` causes this exception: `System Exception - Illegal Instruction`

I've found this older version of nnedi3 built for 64bit which works fine (though has a little bit different syntax -> no etype parameter, and pscrn is boolean)
http://bengal.missouri.edu/~kes25c/nnedi3_64.dll

**Comment by jpsdr** [comment]
Choose another dll file on the release package, maybe you have a Xeon, but it seems you don't  have a Xeon with AVX512 architecture instructions. So, try W7_Core2_AVX2. If you still have an error, try W7_Core2_SSE4.2 (this version, there is a very high probability it'll be fine), and you still have an error, use the simple Release_W7.

**Comment by kaefert** [comment]
It's really strange, I try to test with different dll versions but most of the time I only get "Cannot load file" when avisynth is trying to load the dll. And right now I also get it with the Xeon version. Maybe it is because the machine is busy

But yesterday from what I remember the Xeon version was the only one that did not produce a "Cannot load file" right from the plugin loading statement.

**Comment by jpsdr** [comment]
Be sure to have installed the VS2013 redistribuable and Intel parallel studio 2015 Update 1 redistribuable for the Intel release. It's the only thing i can see that may prevent the load of the dll.

**Comment by jpsdr** [comment]
So ? Problem solved ?

**Comment by kaefert** [comment]
oh. sorry for not replying. well no, I've just given up on using nnedi3 for now and settled for lancos4resize.
I was able to produce a small sample (containing only a fraction of my clips) with nnedi3 but with incredibly slow speed of 0.1fps - which I guess I could tolerate for better quality, but with my complete script with ~100 input clips all in need of resizing it simply never writes a single frame to the output.

I've never managed to get your builds to work, I've only used this seemingly quite old build from there:
http://bengal.missouri.edu/~kes25c/nnedi3_64.dll

I did not want to start installing visual studio and such stuff to get this filter running. maybe I'll try to restructure my automated workflow to produce and reuse intermediate files instead of producing a single avs script and doing all the processing and encoding in one step, but I'm afraid that the intermediate files would be quite large since I guess I would need to use some lossless encoding to prevent encoding errors to multiply because of an too long encoder-decoder-chain.

**Comment by captainadamo** [comment]
jpsdr, why not simply use dynamic dispatching so you don't need so many different DLLs?

**Comment by jpsdr** [comment]
According compiler doc, and i can also understand why, generated code is more efficient when compiling "Use xxx instructions, period !", than "See if you can use instructions xxx, otherwise do something else". So, i choose some kind of CPU/Instructions, and try to generate the most efficient code for it. But it will allmost never beat optimised ASM code. ;)
