### ISSUE TITLE
Latest version?

### ISSUE THREAD

**Issue by Reel-Deal** [jpsdr/NNEDI3#4]
Hi, I was wondering if v0.9.4.9 is the latest version? I ask this because release page says "2 commits to master since this release" with one of commits being "Correction in x64 ASM file".

**Comment by jpsdr** [comment]
Yes, it's the last, several steps until all corrections, but just one step version, didn't want to keep increasing versions with "Correction in x64 ASM file" each time.

**Comment by Reel-Deal** [comment]
OK, thanks for the info.
