### ISSUE TITLE
Question about SIMD optimizations

### ISSUE THREAD

**Issue by magiblot** [jpsdr/NNEDI3#6]
For this plugin you are offering several compilations (dlls), each one in a folder named after a SIMD instruction set.
Does that mean each of these compilations has just one SIMD optimization avaiable?

I have this doubt because other plugins (mvtools, etc) come with all the optimizations in a single dll. It seems like these automatically use the best one avaiable.

**Comment by jpsdr** [comment]
It's just the compiler, which build using CPU specific instructions, meaning you need at least the CPU required, but everything is on all the build. It's just like some minimal requirement.
