### ISSUE TITLE
training own model?

### ISSUE THREAD

**Issue by aka-katto** [jpsdr/NNEDI3#7]
Would it be possible to get the documentation to train my own model? I looked into the readme and source code briefly, please correct me if I'm incorrect

**Comment by jpsdr** [comment]
Sorry, forgot to answer. Core code is not mine, i've just updated the original version, using the vapoursynth version for high bit depth support, but didn't touch anything related to the core and neural network part.
So, unfortunately, i can't help on this request, i have no clue about the training part and information, and i don't have any more documentation.
