### ISSUE TITLE
Green lines at the bottom.

### ISSUE THREAD

**Issue by TbtBI** [jpsdr/NNEDI3#9]
Hi,
```
ColorBars(width=1920, height=1080, pixel_type="yv12")
Crop(0, 138, -0, -138)
PointResize(1920, 1206)
nnedi3()
```
has green lines at the bottom. Tried the latest version and old version from 2017/2016 but those lines are always there.

**Comment by jpsdr** [comment]
I'll investigate later, don't have time right now unfortunately.

**Comment by TbtBI** [comment]
I'm just checking you didn't forget.

**Comment by jpsdr** [comment]
Good idea to check, but i didn't forget, i'll probably not have time too investigate before a long time, as your both reports doesn't seem easy... :(

**Comment by jpsdr** [comment]
But i had time to make a quick test i wanted to do : It also occurs with the original version... :(
(If it occors on original version, not my fault... ^_^ )
Honnestly, i don't know if it's something i'll be able to fix, or even to figure out why.
So, original issue, hard to do, not the time before long.

**Comment by jpsdr** [comment]
Fixed in commit, so next release will be.
